services:
  mcp-for-instrument:
    build: .
    restart: always
    privileged: true
    network_mode: host
    group_add:
      - dialout
    volumes:
      - type: bind
        source: /dev/
        target: /dev/
